baseURL = "http://docs.radio.warwick.ac.uk"
languageCode = "en-us"
title = "RAW Documentation"
theme = "hugo-theme-learn"

[outputs]
	home = [ "HTML", "RSS", "JSON"]

[params]
	themeVariant = "custom"
	disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub Repo"
identifier = "ds"
url = "https://github.com/ConnorPowell/RAWDocumentation"