baseURL = "http://documentation.radio.warwick.ac.uk"
languageCode = "en-us"
title = "RAW Documentation"
theme = "hugo-theme-learn"

[outputs]
	home = [ "HTML", "RSS", "JSON"]

[params]
	themeVariant = "custom"

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub Repo"
identifier = "ds"
url = "http://www.google.com"